### ISSUE TITLE
Yolo Model

### ISSUE THREAD

**Issue by karimyassine97** [XRLabPomerania/Hololens-2-Object-Detection#3]
Hello @yoKurt94
I have tried this project and it worked on my HL2 Device. I wanna add a custom yolo model and I am not sure of how to do so. I saw a script called YoloObjectDetector and I am wondering if you already did that and if so how it works. 
Thank you so much in advance

**Comment by yoKurt94** [comment]
Hi, the Yolo model should work in theory, but I haven't used one yet. You would have to make sure the right in- and outputs are created. The YoloObjectDetector file is not working yet and might be replaced soon. I assume that the yolo model might be to memory intensive which will cause lagging (see "What we learned" [here](https://devpost.com/software/holoyolo)).

**Comment by huaiyizhao** [comment]
I also want to try yolo for object detection and see this issue here. Do you have any plans to implement this feature? I find it difficult to deal with the output of yolo myself, as a newbie to Windows development, Unity, and Visual studio kind of thing. @yoKurt94 Thank you in advance.

**Comment by yoKurt94** [comment]
i would love to give it another go but unfortunately, I don’t have access to the Hololens and a Windows machine currently so I can’t do it right now
